In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split

In [15]:
data = pd.read_csv(r"C:\Users\athar\Desktop\EAI FundamentalAI\diabetes.csv")

In [16]:
from sklearn.svm import SVC

In [17]:
sprt = SVC()

In [53]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

###  Dataset X,Y train and test

In [18]:
X = data.drop('Outcome', axis = 1)

In [19]:
Y = data['Outcome']

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33)

In [21]:
sprt.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

### predict function



In [22]:
pred = sprt.predict(X_test)

In [23]:
pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
print(confusion_matrix(pred,Y_test))

[[156  43]
 [ 11  44]]


### Classification report

In [27]:
print(classification_report(pred,Y_test))

              precision    recall  f1-score   support

           0       0.93      0.78      0.85       199
           1       0.51      0.80      0.62        55

    accuracy                           0.79       254
   macro avg       0.72      0.79      0.74       254
weighted avg       0.84      0.79      0.80       254



In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
param_grid = {'C' : [0.1,1,10,100], 'gamma' : [1,0.1,0.01,0.001,0.0001]}

In [38]:
Gs = GridSearchCV(SVC(),param_grid)

In [39]:
Gs.fit(X_train,Y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [40]:
prediction = Gs.predict(X_test)

In [41]:
Gs.best_params_

{'C': 10, 'gamma': 0.0001}

In [42]:
print(confusion_matrix(Y_test,prediction))

[[155  12]
 [ 41  46]]


In [43]:
print(classification_report(Y_test,prediction))

              precision    recall  f1-score   support

           0       0.79      0.93      0.85       167
           1       0.79      0.53      0.63        87

    accuracy                           0.79       254
   macro avg       0.79      0.73      0.74       254
weighted avg       0.79      0.79      0.78       254



In [ ]:
#plt.scatter(pred,Y_test)